#!/usr/bin/env python3
"""
Generate the Doris built-in function list for the plugin from Doris's own function registry.

Source of truth: the committed Nereids registry lists
  fe/fe-core/src/main/java/org/apache/doris/catalog/Builtin{Scalar,Aggregate,Window,
  TableValued,TableGenerating}Functions.java
Each entry is `scalar(SomeFn.class, "name", "alias1", ...)` (or agg/window/table variants), so the
quoted strings after `.class,` are the function's name + aliases. This is what Doris actually
registers at runtime (FunctionRegistry.registerBuiltinFunctions), so it's more complete and
authoritative than the docs. Not hand-copied: re-run against a newer Doris checkout to refresh.

Signatures (arg/return types) are NOT extracted here — those live on each function class's static
SIGNATURES field and require building fe-core to read. See the fe-core JUnit-dumper approach if
signature/parameter hints are wanted.

Usage:
  tools/generate_doris_functions.py <doris-repo-root> [--out <resource-path>]
"""
import os
import re
import sys
import glob

PLUGIN_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(PLUGIN_DIR, "src", "main", "resources",
                           "com", "brikk", "doris", "functions", "doris-functions.txt")

IDENT = re.compile(r"[A-Za-z][A-Za-z0-9_]*$")
QUOTED = re.compile(r'"([^"]+)"')


def collect(doris_root: str):
    catalog = os.path.join(doris_root, "fe", "fe-core", "src", "main", "java",
                           "org", "apache", "doris", "catalog")
    files = glob.glob(os.path.join(catalog, "Builtin*Functions.java"))
    if not files:
        sys.exit(f"error: no Builtin*Functions.java under {catalog}")
    names = set()
    for path in files:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                # A registration line looks like:  scalar(Abs.class, "abs"),
                #                                   scalar(Substring.class, "substr","substring","mid"),
                idx = line.find(".class,")
                if idx == -1:
                    continue
                for raw in QUOTED.findall(line[idx:]):
                    name = raw.strip().upper()  # function names are case-insensitive in SQL
                    if IDENT.match(name):
                        names.add(name)
    return sorted(names), len(files)


def main():
    args = list(sys.argv[1:])
    out = DEFAULT_OUT
    if "--out" in args:
        i = args.index("--out")
        out = args[i + 1]
        del args[i:i + 2]
    if not args:
        sys.exit("usage: generate_doris_functions.py <doris-repo-root> [--out <path>]")
    names, nfiles = collect(args[0])
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# Doris built-in functions (names + aliases), generated by "
                 "tools/generate_doris_functions.py\n")
        fh.write("# Source: fe/fe-core/.../catalog/Builtin*Functions.java. Do not edit by hand.\n")
        for n in names:
            fh.write(n + "\n")
    print(f"wrote {len(names)} function names from {nfiles} registry files -> {out}")


if __name__ == "__main__":
    main()
